package com.ruoyi.system.outto.dto.yx7881.bean;

import lombok.Data;

@Data
public class CyhxCFInfo {
    //"id":"330605",
    //        "keyname":"账号来源",
    //        "keyid":"code4",
    //        "type":"select",
    //        "value":"我是号主,我买的号",
    //        "must":true,
    String code4;
        //  "id":"330596",
        //        "keyname":"成品号",
        //        "keyid":"antiaddiction",
        //        "type":"select",
        //        "value":"是,否",
        //        "must":true,
    String antiaddiction;
        //"id":"330597",
        //        "keyname":"能否二次",
        //        "keyid":"canSecond",
        //        "type":"select",
        //        "value":"可二次,不可二次",
        //        "must":true,
    String canSecond;
        //"id":"330599",
        //        "keyname":"军衔",
        //        "keyid":"code5",
        //        "type":"text",
        //        "value":null,
        //        "must":true,
    String code5;
        //"id":"330604",
        //        "keyname":"英雄武器数量",
        //        "keyid":"code6",
        //        "type":"text",
        //        "value":null,
        //        "must":true,
    String code6;
        //"id":"9908",
        //        "keyname":"游戏账号",
        //        "keyid":"gameaccount",
        //        "type":"text",
        //        "value":null,
        //        "must":true,
    String gameaccount;
        //"id":"9922",
        //        "keyname":"游戏截图1",
        //        "keyid":"gameimg1",
        //        "type":"image",
        //        "value":null,
        //        "must":false,
    String gameimg1;
        //""id":"330600",
        //        "keyname":"英雄角色数量",
        //        "keyid":"hero",
        //        "type":"text",
        //        "value":null,
        //        "must":true,
    String hero;
        // "id":"330601",
        //        "keyname":"梦幻V数量",
        //        "keyid":"props",
        //        "type":"text",
        //        "value":null,
        //        "must":true,
    String props;
        // "id":"330602",
        //        "keyname":"V枪",
        //        "keyid":"code7",
        //        "type":"checkbox",
        //        "value":"9A91-烈火,AK12-天启,AK47-黑鲨,AK47-黑武士,AK47-火麒麟,AK47-机械迷城,AK47-雷暴,AK47-麒麟,AK47-无影,AN94-超新星,
        //        AWM-裁决,AWM-天龙,Barrett-毁灭,Barrett-极光,Barrett-雷霆,Barrett-朱雀,COP357-雷霆,COP-堕天神,Glock18-武圣,HK417-朱雀,
        //        M200-幻神,M4A1-堕天神,M4A1-黑龙,M4A1-黑骑士,M4A1-雷神,M4A1-雷霆,M4A1-猎神,M4A1-龙血,M4A1-玫瑰精灵,M4A1-千变,M4A1-青龙,
        //        M4A1-死神,M4A1-武圣,M4A1-夜魔,QBZ95-幻兽,RPK-盘龙,Scar-白虎,USP-雷暴,传说暗裔,传说光耀,加特林-炼狱,破空枪刃-夜魔,沙鹰-幻兽,沙鹰-天神,沙鹰-修罗,
        //        汤姆逊-烈龙,传说圣灵,Kar98K-星神,荣耀世冠-雷神,荣耀世冠-火麒麟,荣耀世冠-柯尔特,荣耀世冠-龙啸,传说梦魇,M200-竞技荣光,柯尔特-竞技荣光,擎天-竞技荣光,王者幻神,无",
        //        "must":true,
    String code7;
        //"id":"330603",
        //        "keyname":"角色",
        //        "keyid":"code8",
        //        "type":"checkbox",
        //        "value":"无,凌霄,迷迭香,春,炫,魅影,蝴蝶,瞳,樱,葵,零,审判者,传说女帝,电竞教官-云悠悠,影豹,雨棠,沙漠玫瑰,王者凌霄,王者涂鸦,王者玲珑-小乔,王者-迷迭香,王者零-华冠丽服,
        //        王者葵-惊若翩鸿,王者-零,王者之瞳,狐影,王者复仇,王者蝴蝶,堕落女神,王者王力宏,王者-葵-貂蝉,王者樱-热浪之夏,王者-魅影,王者-零-国色天香,王者-瞳-闭月羞花,王者玲珑,王者-救世主,
        //        王者零-传说之路,雅典娜,鹰",
        //        "must":true,
    String code8;
        //"id":"330696",
        //        "keyname":"音效卡",
        //        "keyid":"code9",
        //        "type":"checkbox",
        //        "value":"无,M4A1-雷神音效卡,AK47-火麒麟音效卡,Barrett-毁灭音效卡,M4A1-黑龙音效卡,Barrett-极光音效卡,AWM-裁决音效卡,QBZ03-金色蔷薇音效卡,
        //        Scar Light-白虎音效卡,Kar98k-星神音效卡,M200-幻神音效卡,M4A1-黑骑士音效卡",
        //        "must":true,
    String code9;
        //"id":"332397",
        //        "keyname":"皮肤",
        //        "keyid":"skin",
        //        "type":"checkbox",
        //        "value":"无,火麒麟-虎牙平台皮肤,火麒麟-斗鱼平台皮肤,雷神-虎牙平台皮肤,QBZ03-冠军之薇,黑龙-冠军之武 ,擎天-冠军之击 ,黑骑士-CFS2021,传奇石头-横秒之巅  ,
        //        麒麟刺-斗鱼平台皮肤 ,擎天-虎牙平台皮肤 ,擎天-冠军之击 ,幻神-周瑜皮肤,幻神-丹凤,幻神-青鹤,雷神-冠军之魄,黑骑士-冠军之势,龙啸-冠军之啸,炼狱-斗鱼平台皮肤,黑骑士-虎牙平台皮肤,
        //        火麒麟-冠军之心,毁灭-冠军之怒,修罗-冠军之魂,雷神-斗鱼平台皮肤,巴雷特-虎牙平台皮肤,雷神-荣耀之魄,毁灭-荣耀之怒,屠龙-荣耀之锋,雷神-荣耀世冠AG,雷神-宠儿-2019MVP,
        //        火麒麟-荣耀世冠AG,屠龙-荣耀世冠AG,雷神-R.LGD-CFPLS18冠军,黑骑士-AG-S4冠军典藏,荣耀之魄-CFPL十周年臻藏版,幻神-宠儿-2021MVP,幻神-冠军之幻,
        //        幻神-AG-CFPLS17冠军",
        //        "must":true,
    String skin;
        // "id":"332398",
        //        "keyname":"武器",
        //        "keyid":"code1",
        //        "type":"checkbox",
        //        "value":"无,M4A1-幻灵,COP 357-幻灵,幻灵之锋,Barrett-电竞装甲,柯尔特-电竞装甲,尼泊尔-电竞装甲,龙啸-堕天神,斩神刀-雷暴,AA-12-雷霆,尼泊尔-雷霆,
        //        金钢伞,王者霜心,王者之霆,王者星神,王者风势,悦蓝-惊涛骇浪,王者凤吟,王者玉峰,王者青龙,M4A1-雷霆王者,Barrett-雷霆王者,COP 357-雷霆王者,雷霆王者之锋,
        //        QBZ-03-王者蔷薇,王者之烈,王者白虎,王者雷怒,王者火魄,王者蔷薇,王者之心,王者之魂,王者之魄,王者之力,王者之怒,王者之锋,王者之影,王者之光,玫瑰精灵-悦动,王者之武,王者之击,
        //        王者之势,王者之翼,王者之幻,王者之啸,王者之刺,天启-悦智,超新星-悦享,王者之灵,王者之戮,猎龙-悦心,炼狱-悦蓝,盘龙-悦心,王者之决,王者之鲨,王者炎心,王者冰魄,王者之城,王者之圣,
        //        王者汪汪-巴雷特,王者AK47-萌萌银发刀锋,王者M4A1-萌萌金发刀锋,王者猛虎M4A1,牛牛-AK,猫猫Cop 357,牛牛AK47-贵族金,黄金猫猫手套,王者-C.A.T,斯泰尔-蝴蝶,
        //        黄金猫猫手套-白鲨",
    String code1;
        // " "id":"9909",
        //        "keyname":"游戏密码",
        //        "keyid":"gamepassword",
        //        "type":"password",
        //        "value":null,
        //        "must":true,
    String gamepassword;
        //"id":"9923",
        //        "keyname":"游戏截图2",
        //        "keyid":"gameimg2",
        //        "type":"image",
        //        "value":null,
        //        "must":false,
    String gameimg2;
        //"id":"9910",
        //        "keyname":"确认输入密码",
        //        "keyid":"gamepassword2",
        //        "type":"password",
        //        "value":null,
        //        "must":true,
    String gamepassword2;
        //"id":"9924",
        //        "keyname":"游戏截图3",
        //        "keyid":"gameimg3",
        //        "type":"image",
        //        "value":null,
        //        "must":false,
    String gameimg3;
        // "id":"9911",
        //        "keyname":"游戏角色名称",
        //        "keyid":"gamerole",
        //        "type":"text",
        //        "value":null,
        //        "must":true,
    String gamerole;
        //"id":"9925",
        //            "keyname":"游戏截图4",
        //            "keyid":"gameimg4",
        //            "type":"image",
        //            "value":null,
        //            "must":false,
    String gameimg4;
        //  "id":"9926",
        //        "keyname":"游戏截图5",
        //        "keyid":"gameimg5",
        //        "type":"image",
        //        "value":null,
        //        "must":false,
    String gameimg5;
    // "id":"334601",
    //        "keyname":"常用微信号",
    //        "keyid":"weixin",
    //        "type":"text",
    //        "value":null,
    //        "must":true,
    String weixin;
}
