package com.ruoyi.system.outto.dto.yx7881.bean;

import lombok.Data;

@Data
public class CyhxQZWZInfo {
    //"id":"324798",
    //            "keyname":"账号来源",
    //            "keyid":"code5",
    //            "type":"select",
    //            "value":"我是号主,我买的号",
    //            "must":true,
    String code5;
    //"id":"292169",
    //            "keyname":"游戏账号",
    //            "keyid":"gameaccount",
    //            "type":"text",
    //            "value":null,
    //            "must":true,
    String gameaccount;
    //"id":"292170",
    //            "keyname":"游戏密码",
    //            "keyid":"gamepassword",
    //            "type":"password",
    //            "value":null,
    //            "must":true,
    String gamepassword;
    // "id":"292171",
    //            "keyname":"确认游戏密码",
    //            "keyid":"gamepasswordqr",
    //            "type":"password",
    //            "value":null,
    //            "must":true,
    String gamepasswordqr;
    //"id":"292172",
    //            "keyname":"游戏角色名称",
    //            "keyid":"gamerole",
    //            "type":"text",
    //            "value":null,
    //            "must":true,
    String gamerole;
    //"id":"323802",
    //            "keyname":"成人号",
    //            "keyid":"antiaddiction",
    //            "type":"select",
    //            "value":"是,否",
    //            "must":true,
    String antiaddiction;
    // "id":"334600",
    //            "keyname":"常用微信号",
    //            "keyid":"weixin",
    //            "type":"text",
    //            "value":null,
    //            "must":true,
    String weixin;
    // "id":"330302",
    //            "keyname":"能否二次",
    //            "keyid":"canSecond",
    //            "type":"select",
    //            "value":"可二次,不可二次",
    //            "must":true,
    String canSecond;
    // "id":"323796",
    //            "keyname":"VIP等级",
    //            "keyid":"code2",
    //            "type":"select",
    //            "value":"V1,V2,V3,V4,V5,V6,V7,V8,V9,V10",
    //            "must":true,
    String code2;
    //"id":"325500",
    //            "keyname":"至尊套装",
    //            "keyid":"code7",
    //            "type":"checkbox",
    //            "value":"无,王者之影至尊套,王者之武至尊套,王者之翼至尊套,王者之势至尊套,王者之戮至尊套,王者之城至尊套,王者之力至尊套,王者之光至尊套,王者之怒至尊套,王者之心至尊套,王者之圣至尊套,
    //            王者之魄至尊套,王者之狱至尊套,王者之神至尊套,王者幻神至尊套,王者之烈至尊套,王者之启至尊套,王者之腾至尊套",
    //            "must":true,
    String code7;
    //"id":"325499",
    //            "keyname":"王者套装",
    //            "keyid":"code8",
    //            "type":"checkbox",
    //            "value":"无,王者之心套,王者之魄套,王者之怒套,王者之翼套,王者之影套,王者之势套,王者之武套,王者之光套,王者之力套,王者之戮套,王者之圣套,王者之城套,王者之神套,王者幻神套,
    //            王者之烈套,王者之狱套,王者之启套,王者之腾套",
    //            "must":true,
    String code8;
    // "id":"323797",
    //            "keyname":"王者武器",
    //            "keyid":"code3",
    //            "type":"checkbox",
    //            "value":"无,王者之心,王者之影,王者之翼,王者之魄,王者之武,王者之势,王者之戮,王者之怒,王者之光,王者之力,王者之魂,王者之灵,王者之轮,王者之电,王者之锋,王者之啸,王者之刺,
    //            王者之击,王者之烈,王者之圣,王者之迹,王者之痕,王者之城,王者之神,王者幻神,王者之狱,王者之腾,王者之仞,王者之隐",
    //            "must":true,
    String code3;
    //"id":"323800",
    //            "keyname":"特殊武器",
    //            "keyid":"code4",
    //            "type":"checkbox",
    //            "value":"无,黑龙魂,M4A1-星象,M200-幻神,AK47-孟德,COP 357-星象,COP 357-雷神,AWM-妙才,81式-瑜,TAC-慈,AK47-策,M4A1-仲达,
    //            AK47-奉先,巴雷特-定军,MK47-仁德,M4A1-游骑兵,M4A1-七色宝葫,斯泰尔-蝴蝶,COP 357-雷霆",
    //            "must":true,
    String code4;
    // "id":"331796",
    //            "keyname":"皮肤",
    //            "keyid":"code10",
    //            "type":"checkbox",
    //            "value":"无,王者之城-冰霜奇迹,王者幻神-冰霜奇迹,王者之戮-紫电熔岩,王者之戮-燃竞之巅,王者之势-冰霜奇迹,王者之光-HeartSho,王者之翼-燃竞之巅,王者之力-紫电熔岩,
    //            王者之力-燃竞之巅,王者之影-紫电熔岩,王者之影-燃竞之巅,王者之怒-紫电熔岩,王者之怒-燃竞之巅,王者之怒-HeartSho,王者之魄-紫电熔岩,王者之魄-燃竞之巅,王者之魄-HeartSho,
    //            王者之心-紫电熔岩,王者之心-燃竞之巅,王者之心-HeartSho,孟德-过载,仲达-过载,妙才-过载,81瑜-龙腾之力,幻神-战舞,定军-忿魔,王者之魂紫电熔岩,王者之锋紫电熔岩,
    //            王者之灵紫电熔岩,王者之啸紫电熔岩,王者之轮冰霜奇迹,M4A1-星象-璀璨星辰,AK47-策-霸魂,AK-47奉先-无双",
    //            "must":false,
    String code10;
    //"id":"324540",
    //            "keyname":"角色",
    //            "keyid":"code11",
    //            "type":"checkbox",
    //            "value":"无,曼陀罗09-X,零-水下丽影,雅典娜,职场灵狐-赛事经理,岚兮儿,春,乔月,晴雅,雾萌萌,雨墨,王者-零,云悠悠,傲骨,蝴蝶,关小雨,英雄兰,瞳,樱,子涵,蝉",
    //            "must":true,
    String code11;
    //"id":"332097",
    //            "keyname":"手雷套",
    //            "keyid":"code9",
    //            "type":"checkbox",
    //            "value":"无,王者之心手雷弹,王者之心闪光弹,王者之心烟雾弹,王者之影手雷弹,王者之影闪光弹,王者之影烟雾弹,王者之翼手雷弹,王者之翼闪光弹,王者之翼烟雾弹,王者之势手雷弹,王者之势闪光弹,
    //            王者之势烟雾弹,王者之圣手雷弹,王者之圣闪光弹,王者之圣烟雾弹,王者之兽手雷,王者之兽闪光弹,王者之兽烟雾弹",
    //            "must":true,
    String code9;
    // "id":"323798",
    //            "keyname":"英雄武器V数量",
    //            "keyid":"code12",
    //            "type":"text",
    //            "value":null,
    //            "must":true,
    String code12;
    //"id":"323799",
    //            "keyname":"王者武器V数量",
    //            "keyid":"code1",
    //            "type":"text",
    //            "value":null,
    //            "must":true,
    String code1;

}
