package com.ruoyi.system.outto.dto.yx7881.bean;

import lombok.Data;

@Data
public class HpjyInfo {

//"id":"324796",
//        "keyname":"账号来源",
//        "keyid":"code5",
//        "type":"select",
//        "value":"我是号主,我买的号",
//        "must":true,
    String code5;
//    "id":"323657",
//        "keyname":"成人号",
//        "keyid":"antiaddiction",
//        "type":"select",
//        "value":"是,否",
//        "must":true,
    String antiaddiction;
//"id":"330298",
//        "keyname":"能否二次",
//        "keyid":"canSecond",
//        "type":"select",
//        "value":"可二次,不可二次",
//        "must":true,
    String canSecond;
    //"id":"295301",
    //        "keyname":"游戏账号",
    //        "keyid":"gameaccount",
    //        "type":"text",
    //        "value":null,
    //        "must":true,
    String gameaccount;
    //"id":"295302",
    //        "keyname":"游戏密码",
    //        "keyid":"gamepassword",
    //        "type":"password",
    //        "value":null,
    //        "must":true,
    String gamepassword;
    //"id":"295303",
    //        "keyname":"确认游戏密码",
    //        "keyid":"gamepasswordqr",
    //        "type":"password",
    //        "value":null,
    //        "must":true,
    String gamepasswordqr;
    //"id":"334599",
    //            "keyname":"常用微信号",
    //            "keyid":"weixin",
    //            "type":"text",
    //            "value":null,
    //            "must":true,
    String weixin;
    //"id":"323116",
    //        "keyname":"热门载具",
    //        "keyid":"code6",
    //        "type":"checkbox",
    //        "value":"无,路特斯ELETRE(电光紫),路特斯ELETRE(花绽灰),路特斯ELETRE(冰川蓝),路特斯EVIJA(电光紫),路特斯EVIJA(星际黄),兰博基尼Estoque银翼灰,
    //        兰博基尼Estoque炫光金,兰博基尼Estoque尊享铂,兰博基尼AventadorSVJ翡翠绿,兰博基尼AventadorSVJ炫光金,兰博基尼AventadorSVJ尊享铂,兰博基尼URUS明艳黄,
    //        兰博基尼URUS炫光金,兰博基尼URUS尊享铂,玛莎拉蒂金色,玛莎拉蒂蓝色,玛莎拉蒂粉色,南瓜车,Model3白色,Model3银色,Model3紫色,ModelX白色,ModelX银色,ModelX紫色,
    //        合金龙骨蓝色,合金龙骨绿色,合金龙骨红色,阿斯顿马丁DBS红色,阿斯顿马丁DBS绿色,阿斯顿马丁DBS金色,阿斯顿马丁DBX蓝色,阿斯顿马丁DBX橙色,阿斯顿马丁DBX金色,僚机-萌兔起飞,
    //        空客H135-蔚蓝之翼,空客H135-恋语之翼,双人摩托双刃魅影红色,双人摩托双刃魅影绿色,双人摩托双刃魅影金色,特斯拉Roadster水滴蓝,特斯拉Roadster沁心粉,特斯拉Roadster尊享铂,
    //        特斯拉Cybertruck极昼黑,特斯拉Cybertruck荒芜蓝,特斯拉Cybertruck镭光铂,快艇自由的鲸,塞莎KL27深潜蓝,塞莎KL27霓虹粉,塞莎KL27鲸之蓝,软萌羊咩咩,俏皮小熊猫,
    //        鬼马风驰,萌喵橘座,灵鼠银迹,焰龙咆哮,海龙奔腾,金龙耀世,急速兔兔车,双人摩托梦幻火箭",
    //        "must":true,
    String code6;
    //"id":"324597",
    //        "keyname":"优质套装",
    //        "keyid":"code7",
    //        "type":"checkbox",
    //        "value":"无,角色-零号机,角色-初号机,角色-2号机,赛罗闪耀型,闪耀迪迦,极限特训,快乐主宰,幻影战神,星际漫游者,数码大师,未来战士,南瓜骑士,粉色回忆,怪诞乔克,荒野猎神,甜心巧克力,
    //        宝贝奶油派,天使彩虹糖,深渊皇后,金曜白虎,木曜青龙,水曜玄武,火曜朱雀,土曜战麒,银河战甲,雪国幻梦,守护骑士,蝶舞迷情,梦幻火箭,精灵迷巫,星之信仰,华贵君王,天启纪元,麻辣鲜香锅,金风玉露,金属狂野,
    //        精灵氛围,智能音符,缤纷油彩,放客神游,深海曼妙,PEL轰鸣竞梦者,古堡领主,天禅智恒,慧云及圣,狩月元帅,琉璃脉冲,新星烈龙,向日葵,甜蜜誓约,心之恋语,极致幻想,星空之魅,扶摇飞仙,幻彩马卡龙,
    //        花间之火,潮汐统领,锦绣火鲤,鳞翅贤者,迷蝶贵族,星点战士,铁甲悍将,黄蜂伯爵,草莓生巧,诡面斩,俏皮狐尾,香水柠檬,苍蓝魅影,翡翠骑士,炫金战神,童趣迷兔,冰霜白皇,炙焰红王,银刃塞罗,暗翼战神,
    //        王牌四分卫,绮梦青鸾,星之彼岸,相思残雪,甜梦冰蝶,绿野柔风,馨动时刻,炙焰赤龙,飓风飞鹰,虎啸骄阳,枪炮玫瑰,蜜桃特工,蝶舞蔷薇,桀骜红莲,显圣真君,铁血龙王,葫芦兄弟,桀骜红莲,显圣真君,铁血龙王,
    //        焰龙焚天,银龙傲海,骨龙祭渊,沙场疾风,花影阑珊,俏雪寒霜,吟月归客,齐天大圣,洛天依,红伞翩翩,黑伞漫漫,黄伞悠悠,海渊国主,暗夜玫瑰,蓝莓炮弹",
    //        "must":true,
    String code7;
    //"id":"323119",
    //        "keyname":"热门套装",
    //        "keyid":"code8",
    //        "type":"checkbox",
    //        "value":"无,老版火箭少女101,冥河战士,巡查员上衣,都市猎人,奇异狩猎者,黄金大亨,浪漫波比,仓鼠灰灰,折纸暴龙,深海小丑鱼,胖达团团,胖达圆圆,银河圣歌,闪耀星光,淡雅花蕊,奇迹天团,
    //        星光纪元,蔷薇魔法师,云纹魔法士,玲珑飞花,维京奇缘,萌神柯基,爱崽白熊,花面小丑,狂徒小丑,黑色刀锋,战斗矩阵,滨海厨神,好奇恐龙,奇趣企鹅,潮萌小黄鸭,威严将相,圣殿骑士,九霄,裁决冥王,赛博空间,
    //        五号元素,清香五月粽,软嫩糖心蛋,云丝凤蟒,新侠客行,夏日音浪,人鱼之吻,摇滚狂鲨,东方飞龙,爱神,智慧之神,众神之王,PEL摇滚竞梦者,PEL躁动竞梦者,乘风破浪,神秘黑猫,软萌银虎,大橘为重,顽皮玉兔,
    //        白月香洋装,风华少年志,不夜海上花,破蛋小黄鸡,沙漠守护者,罗小黑, 暴走罗小黑,激萌罗小黑,红酒骑士,舞夜骑士,机械冒险家,机械英豪,机械征服者,PEC最牛战神,驯鹿叮当,动感兔斯基人偶服,神奈川冲浪里,
    //        安第斯皇冠,荷鲁斯之眼,暗夜契约,纯白誓言,白虎圣者,青龙圣者,玄武圣者,朱雀圣者,丝绸行者,神秘舞者,粉甜马卡龙,蓝甜马卡龙,玫瑰恋情,本愿之火,辉星之火,浪客战士,静谧青瓷,娴静芝兰,深山诡影,
    //        萌主吾皇,薄荷蓝莓,抹茶蜜豆,隐空刺,影双刃,怪兽之王,韶华初心,梦之呓语,浪漫樱花,冰爽海盐,滑板小狐,山经魅狐,诡谋托雷基亚,骁骑迪迦,暗黑裁决,暗影爵士,炫光贝贝,超能拳王,击剑大师,星河入梦,
    //        梦起落英,梨园星光,快乐星愿,星梦畅游,灵绣,微雨春柳,暖风夏荷,鹤发童颜,蝎王蛇后,S1赛事,S2赛事,S3赛事,S4赛事,S5赛事,S6赛事,SS1特训,SS2特训,SS3特训,SS4特训,SS5特训,
    //        SS6特训,SS7特训,SS8特训,SS9特训,SS10特训,SS11特训,SS12特训,SS13特训,SS14特训,SS15特训,SS16特训,SS17特训,SS18特训",
    //        "must":true,
    String code8;
    //"id":"323120",
    //        "keyname":"热门枪械",
    //        "keyid":"code9",
    //        "type":"checkbox",
    //        "value":"无,SCAR-L甜梦小狐,UZI筑梦精灵,DP-28幻梦音符,AWM橘柚倾心,M762冷魅冰骑,UMP恐龙拽拽,Kar98K绿意幻情,Mini14绚金瑰梦,野牛流星咚咚,M762甜心娃娃,
    //        M24暗星紫秘,GROZA焦糖拿铁,SKS碧影闪光,SCARL青春物语,AKM百合蜜语,AKM甜心宝贝,M24星之信仰,M416五爪金龙,Mini14龙虾霸霸,SCAR-L梦幻火箭,UMP45雪国精灵,
    //        AKM炫紫旋律,Kar98K伏魔团,M762甜蜜誓约,M416心之恋语,DP-28扶摇飞仙,AWM花间之火,Mini14荧光虫舞,SKS诡面斩,GROZA香水柠檬,M762激战未来,SCAR-L童趣迷兔,
    //        Kar98K暗翼战神,UZI绮梦青鸾,AUG星之彼岸,UMP45相思残雪,汤姆逊怪笑疯兔,AKM梦之光华,VSS烈焰拳霸,M249古战神甲,DP-28枪炮玫瑰,M16A4葫芦兄弟,SCAR-L机甲封神,
    //        AWM焰龙焚天,M416风花雪月,MG3洛神天依,Vector红伞翩翩,S12K海渊国主,SLR暗夜玫瑰,M249蓝莓炮弹",
    //        "must":true,
    String code9;
    // "id":"324320",
    //        "keyname":"粉装数量",
    //        "keyid":"code1",
    //        "type":"text",
    //        "value":null,
    //        "must":true,
    String code1;
    // "id":"324321",
    //        "keyname":"特效枪数量",
    //        "keyid":"code2",
    //        "type":"text",
    //        "value":null,
    //        "must":true,
    String code2;
    //"id":"323658",
    //        "keyname":"套装数量",
    //        "keyid":"code3",
    //        "type":"text",
    //        "value":null,
    //        "must":true,
    String code3;
    //"id":"323659",
    //        "keyname":"枪皮数量",
    //        "keyid":"code4",
    //        "type":"text",
    //        "value":null,
    //        "must":true,
    String code4;
    //"id":"334835",
    //            "keyname":"王牌印记数量",
    //            "keyid":"code10",
    //            "type":"text",
    //            "value":null,
    //            "must":true,
    String code10;
}
